name: smoke-Mac

on:
  schedule:
    - cron: '34 4 * * 2,4' # every Tuesday and Thursday at 04:34
  workflow_dispatch:


jobs:
  smokeARM:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install openMHA
      run: brew install openmha/tap/openmha
    - name: show version
      run: mha cmd=quit
    - name: run
      run: mha nchannels_in=4 srate=16000 fragsize=32 iolib=MHAIOFile io.in=/opt/homebrew/share/openmha/examples/06-binaural-beamformer/2speaker_4ch_16k.wav io.out=/dev/null mhalib=overlapadd mha.plugin_name=bmfwf mha.bmfwf.model_file=/opt/homebrew/share/openmha/examples/34-DNN-based-speech-enhancement/model_bmfwf.pt mha.fftlen=128 mha.wnd.len=64 cmd=start cmd=quit
  smokeIntel:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - name: install openMHA
      run: brew install openmha/tap/openmha
    - name: show version
      run: mha cmd=quit
    - name: run
      run: mha nchannels_in=4 srate=16000 fragsize=32 iolib=MHAIOFile io.in=/usr/local/share/openmha/examples/06-binaural-beamformer/2speaker_4ch_16k.wav io.out=/dev/null mhalib=overlapadd mha.plugin_name=bmfwf mha.bmfwf.model_file=/usr/local/share/openmha/examples/34-DNN-based-speech-enhancement/model_bmfwf.pt mha.fftlen=128 mha.wnd.len=64 cmd=start cmd=quit
