name: smoke-24.04

on:
  workflow_dispatch:
    

jobs:
  smoke:
    runs-on: ubuntu-latest
    container: # github actions does not yet have ubuntu 24.04. Use docker instead.
      image: ubuntu:24.04
    steps:
    - name: install required packages
      run: apt-get -y update && apt-get -y install wget gnupg2 sudo software-properties-common
    - uses: actions/checkout@v2
    - name: apt repository for openMHA releases
      run: wget -qO- http://apt.hoertech.de/openmha-packaging.pub | sudo tee /etc/apt/trusted.gpg.d/openmha-packaging.asc &&
           sudo apt-add-repository 'deb http://apt.hoertech.de/ noble universe' &&
           sudo apt-add-repository 'deb http://aptdev.hoertech.de/ noble universe' # needed now for bmfwf, remove after next release
    - name: install openMHA
      run: sudo apt install -y libopenmha-dev openmha-examples
    - name: show version
      run: dpkg -l openmha
    - name: run
      run: mha nchannels_in=4 srate=16000 fragsize=32 iolib=MHAIOFile io.in=/usr/share/openmha/examples/06-binaural-beamformer/2speaker_4ch_16k.wav io.out=/dev/null mhalib=overlapadd mha.plugin_name=bmfwf mha.bmfwf.model_file=/usr/share/openmha/examples/34-DNN-based-speech-enhancement/model_bmfwf.pt mha.fftlen=128 mha.wnd.len=64 cmd=start cmd=quit
